// Render a rent receipt to a shareable PNG — no external library, just the
// Canvas 2D API. On a phone this can go straight into WhatsApp via the native
// share sheet; everywhere else it downloads. People screenshot EcoCash/M-Pesa
// confirmations constantly, so a clean branded image is the format tenants
// actually forward as proof.
import { money, fullName, fmtDate } from './format.js'
import { formatPeriod } from './billing.js'

const W = 720
const PAD = 48
const SCALE = 2 // render at 2x for crisp text

function rows(payment, tenant, property) {
  const out = [
    ['Receipt No.', payment.receipt_no || '—'],
    ['Date', fmtDate(payment.approved_at || payment.paid_date)],
    ['Tenant', fullName(tenant)],
  ]
  if (property) out.push(['Property', `${property.name}${tenant?.unit ? ` · Unit ${tenant.unit}` : ''}`])
  else if (tenant?.unit) out.push(['Unit', tenant.unit])
  out.push(['Billing period', formatPeriod({ from: payment.period_from, to: payment.period_to })])
  out.push(['Method', payment.method || '—'])
  if (payment.reference || payment.gateway_ref) out.push(['Reference', payment.reference || payment.gateway_ref])
  if (Number(payment.credit_amount) > 0) out.push(['Credit carried forward', money(payment.credit_amount)])
  return out
}

export function renderReceiptCanvas({ payment, tenant, manager, property, brandName = 'RentLoja', brandColor = '#1d6fe0' }) {
  const list = rows(payment, tenant, property)
  const rowH = 44
  const headH = 150
  const totalBlock = 120
  const footH = 70
  const H = headH + list.length * rowH + totalBlock + footH + PAD

  const cvs = document.createElement('canvas')
  cvs.width = W * SCALE
  cvs.height = H * SCALE
  const ctx = cvs.getContext('2d')
  ctx.scale(SCALE, SCALE)
  const font = (size, weight = '400') => `${weight} ${size}px -apple-system, "Segoe UI", Roboto, Arial, sans-serif`

  // Card background
  ctx.fillStyle = '#fbf9f4'; ctx.fillRect(0, 0, W, H)
  ctx.fillStyle = brandColor; ctx.fillRect(0, 0, W, 8) // brand bar

  // Header
  ctx.textBaseline = 'alphabetic'
  ctx.fillStyle = '#1a1714'; ctx.font = font(34, '700')
  ctx.fillText(brandName, PAD, 74)
  ctx.fillStyle = '#6b6258'; ctx.font = font(15)
  ctx.fillText('Official Rent Receipt', PAD, 98)

  // PAID stamp
  ctx.save()
  ctx.translate(W - PAD - 58, 66); ctx.rotate(-6 * Math.PI / 180)
  ctx.strokeStyle = '#2e8b57'; ctx.lineWidth = 2.5
  ctx.strokeRect(-52, -26, 104, 40)
  ctx.fillStyle = '#2e8b57'; ctx.font = font(20, '800'); ctx.textAlign = 'center'
  ctx.fillText('PAID', 0, 2)
  ctx.restore(); ctx.textAlign = 'left'

  // Divider
  ctx.strokeStyle = '#1a1714'; ctx.lineWidth = 2
  ctx.beginPath(); ctx.moveTo(PAD, headH - 22); ctx.lineTo(W - PAD, headH - 22); ctx.stroke()

  // Rows
  let y = headH + 6
  for (const [k, v] of list) {
    ctx.fillStyle = '#6b6258'; ctx.font = font(16)
    ctx.fillText(k, PAD, y)
    ctx.fillStyle = '#1a1714'; ctx.font = font(16, '600'); ctx.textAlign = 'right'
    ctx.fillText(String(v), W - PAD, y)
    ctx.textAlign = 'left'
    ctx.strokeStyle = '#ece7dd'; ctx.lineWidth = 1
    ctx.beginPath(); ctx.moveTo(PAD, y + 14); ctx.lineTo(W - PAD, y + 14); ctx.stroke()
    y += rowH
  }

  // Total
  y += 18
  ctx.fillStyle = '#1a1714'; ctx.font = font(18, '600')
  ctx.fillText('Amount paid', PAD, y + 20)
  ctx.font = font(40, '800'); ctx.textAlign = 'right'
  ctx.fillText(money(payment.amount), W - PAD, y + 26)
  ctx.textAlign = 'left'

  // Footer
  ctx.fillStyle = '#6b6258'; ctx.font = font(13); ctx.textAlign = 'center'
  ctx.fillText(`Issued by ${fullName(manager)} · Thank you for your payment.`, W / 2, H - 32)
  ctx.fillStyle = '#a89f90'; ctx.font = font(11)
  ctx.fillText('Generated by RentLoja', W / 2, H - 14)
  ctx.textAlign = 'left'

  return cvs
}

function canvasToBlob(cvs) {
  return new Promise((resolve) => cvs.toBlob((b) => resolve(b), 'image/png', 0.95))
}

// Share the receipt as a PNG. On a phone with the Web Share API this opens the
// native sheet (WhatsApp, etc.) with the image attached; otherwise it downloads.
// Returns 'shared' | 'downloaded'.
export async function shareReceiptImage(opts) {
  const cvs = renderReceiptCanvas(opts)
  const blob = await canvasToBlob(cvs)
  const name = `receipt-${opts.payment.receipt_no || Date.now()}.png`
  const file = new File([blob], name, { type: 'image/png' })

  if (navigator.canShare && navigator.canShare({ files: [file] })) {
    try {
      await navigator.share({ files: [file], title: 'Rent receipt', text: `Rent receipt — ${fullName(opts.tenant)}` })
      return 'shared'
    } catch (e) {
      if (e?.name === 'AbortError') return 'shared' // user closed the sheet — not an error
    }
  }

  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url; a.download = name
  document.body.appendChild(a); a.click(); a.remove()
  setTimeout(() => URL.revokeObjectURL(url), 1000)
  return 'downloaded'
}
